package controller;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import model.DAOtraitement;
import model.traitement;

public class traitementAjouterController {
    @FXML private TextField txtNom;
    @FXML private TextField txtPrix;
    @FXML private TextField txtFoisParJour;
    @FXML private TextField txtType;
    @FXML private TextField txtDuree;
    @FXML private Button btnAjouter;
    @FXML
    private Button btnCancel;
    
    private final DAOtraitement daoTraitement = new DAOtraitement();
    private traitementController parentController;
    public void setParentController(traitementController controller) {
    this.parentController = controller;
}
    @FXML
    private void handleAjouter() {
        try {
            if (parentController != null) {
    parentController.refreshTable();
} else {
    System.out.println("parentController est null !");
}
            if (!validateFields()) {
                return;
            }

            traitement newTraitement = createTraitementFromFields();
            
            if (daoTraitement.addTraitement(newTraitement)) {
                parentController.refreshTable();
                closeWindow();
                showSuccessAlert("Traitement ajouté avec succès");
            } else {
                showErrorAlert("Échec de l'ajout du traitement");
            }
        } catch (NumberFormatException e) {
            showErrorAlert("Veuillez entrer des valeurs numériques valides pour le prix et le nombre de fois par jour");
        }
    }

    private boolean validateFields() {
        if (txtNom.getText().isEmpty() || 
            txtType.getText().isEmpty() || 
            txtDuree.getText().isEmpty()) {
            showErrorAlert("Veuillez remplir tous les champs obligatoires");
            return false;
        }
        
        try {
            Double.parseDouble(txtPrix.getText());
            Integer.parseInt(txtFoisParJour.getText());
        } catch (NumberFormatException e) {
            showErrorAlert("Le prix doit être un nombre et les fois/jour un entier");
            return false;
        }
        
        return true;
    }

    private traitement createTraitementFromFields() {
        return new traitement(
            0, // ID will be generated by database
            txtNom.getText().trim(),
            Double.parseDouble(txtPrix.getText()),
            Integer.parseInt(txtFoisParJour.getText()),
            txtType.getText().trim(),
            txtDuree.getText().trim()
        );
    }

    private void showErrorAlert(String message) {
        showAlert("Erreur", message, Alert.AlertType.ERROR);
    }

    private void showSuccessAlert(String message) {
        showAlert("Succès", message, Alert.AlertType.INFORMATION);
    }

    private void showAlert(String title, String message, Alert.AlertType type) {
        Alert alert = new Alert(type);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }

    private void closeWindow() {
        Stage stage = (Stage) btnAjouter.getScene().getWindow();
        stage.close();
    }
@FXML
    private void handleCancel() {
        closeWindow();
    }
    

    private void showAlert(Alert.AlertType type, String title, String message) {
        Alert alert = new Alert(type);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}